"""add_auditoria_and_hitl_tables

Revision ID: 187fd47fed85
Revises: c92a8d306bb8
Create Date: 2026-03-16 05:43:41.855761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '187fd47fed85'
down_revision: Union[str, Sequence[str], None] = 'c92a8d306bb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
