"""Add Bias Report tables

Revision ID: 1e489178d31e
Revises: eda03ad677f2
Create Date: 2026-03-07 17:04:15.938036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1e489178d31e'
down_revision: Union[str, Sequence[str], None] = 'eda03ad677f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    from sqlalchemy import inspect as sa_inspect
    bind = op.get_bind()
    existing = sa_inspect(bind).get_table_names()

    if 'bias_report' not in existing:
        op.create_table('bias_report',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.Column('bias_score', sa.Float(), nullable=False),
        sa.Column('metrics_payload', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('recommendations', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_bias_report_tenant_id'), 'bias_report', ['tenant_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bias_report_tenant_id'), table_name='bias_report')
    op.drop_table('bias_report')
    # ### end Alembic commands ###
