"""Add User table for IAM Phase 1

Revision ID: c92a8d306bb8
Revises: 1e489178d31e
Create Date: 2026-03-15 20:24:01.431082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c92a8d306bb8'
down_revision: Union[str, Sequence[str], None] = '1e489178d31e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    from sqlalchemy import inspect as sa_inspect
    bind = op.get_bind()
    existing = sa_inspect(bind).get_table_names()

    if 'lexia_user' not in existing:
        op.create_table('lexia_user',
        sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('role', sa.Enum('admin', 'legislator', 'analyst', 'readonly', name='userrole'), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_lexia_user_email'), 'lexia_user', ['email'], unique=True)
        op.create_index(op.f('ix_lexia_user_tenant_id'), 'lexia_user', ['tenant_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lexia_user_tenant_id'), table_name='lexia_user')
    op.drop_index(op.f('ix_lexia_user_email'), table_name='lexia_user')
    op.drop_table('lexia_user')
    # ### end Alembic commands ###
