"""Add HITL review tables

Revision ID: eda03ad677f2
Revises: f94b189c9060
Create Date: 2026-03-07 16:38:09.881210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eda03ad677f2'
down_revision: Union[str, Sequence[str], None] = 'f94b189c9060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    from sqlalchemy import inspect as sa_inspect
    bind = op.get_bind()
    existing = sa_inspect(bind).get_table_names()

    if 'hitl_review' not in existing:
        op.create_table('hitl_review',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('impact_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', name='hitlstatus'), nullable=False),
        sa.Column('original_request', sa.JSON(), nullable=True),
        sa.Column('ai_proposed_response', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('reviewer_id', sa.Integer(), nullable=True),
        sa.Column('reviewer_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('reviewed_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_hitl_review_request_id'), 'hitl_review', ['request_id'], unique=False)
        op.create_index(op.f('ix_hitl_review_tenant_id'), 'hitl_review', ['tenant_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hitl_review_tenant_id'), table_name='hitl_review')
    op.drop_index(op.f('ix_hitl_review_request_id'), table_name='hitl_review')
    op.drop_table('hitl_review')
    # ### end Alembic commands ###
