"""Add subscription table

Revision ID: f4ffa005e048
Revises: 187fd47fed85
Create Date: 2026-03-25 11:53:57.495918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f4ffa005e048'
down_revision: Union[str, Sequence[str], None] = '187fd47fed85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lexia_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notify_email', sa.Boolean(), nullable=False),
    sa.Column('notify_webhook', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lexia_subscription_tenant_id'), 'lexia_subscription', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_lexia_subscription_user_id'), 'lexia_subscription', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lexia_subscription_user_id'), table_name='lexia_subscription')
    op.drop_index(op.f('ix_lexia_subscription_tenant_id'), table_name='lexia_subscription')
    op.drop_table('lexia_subscription')
    # ### end Alembic commands ###
