"""Add IP Registry tables

Revision ID: f94b189c9060
Revises: 
Create Date: 2026-03-07 16:33:51.240063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f94b189c9060'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('license_type', sa.Enum('OPEN', 'RESTRICTED', 'COMMERCIAL', 'UNKNOWN', name='iplicensetype'), nullable=False),
    sa.Column('owner', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_source_name'), 'data_source', ['name'], unique=True)
    op.create_table('tenant',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('schema_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_domain'), 'tenant', ['domain'], unique=True)
    op.create_index(op.f('ix_tenant_name'), 'tenant', ['name'], unique=False)
    op.create_index(op.f('ix_tenant_schema_name'), 'tenant', ['schema_name'], unique=True)
    op.create_table('auditorialog',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module_used', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_resource', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ai_model_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('xai_trace_payload', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditorialog_module_used'), 'auditorialog', ['module_used'], unique=False)
    op.create_index(op.f('ix_auditorialog_request_id'), 'auditorialog', ['request_id'], unique=False)
    op.create_index(op.f('ix_auditorialog_tenant_id'), 'auditorialog', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_auditorialog_timestamp'), 'auditorialog', ['timestamp'], unique=False)
    op.create_index(op.f('ix_auditorialog_user_id'), 'auditorialog', ['user_id'], unique=False)
    op.create_table('data_lineage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('document_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('usage_context', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_lineage_request_id'), 'data_lineage', ['request_id'], unique=False)
    op.create_index(op.f('ix_data_lineage_tenant_id'), 'data_lineage', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_lineage_tenant_id'), table_name='data_lineage')
    op.drop_index(op.f('ix_data_lineage_request_id'), table_name='data_lineage')
    op.drop_table('data_lineage')
    op.drop_index(op.f('ix_auditorialog_user_id'), table_name='auditorialog')
    op.drop_index(op.f('ix_auditorialog_timestamp'), table_name='auditorialog')
    op.drop_index(op.f('ix_auditorialog_tenant_id'), table_name='auditorialog')
    op.drop_index(op.f('ix_auditorialog_request_id'), table_name='auditorialog')
    op.drop_index(op.f('ix_auditorialog_module_used'), table_name='auditorialog')
    op.drop_table('auditorialog')
    op.drop_index(op.f('ix_tenant_schema_name'), table_name='tenant')
    op.drop_index(op.f('ix_tenant_name'), table_name='tenant')
    op.drop_index(op.f('ix_tenant_domain'), table_name='tenant')
    op.drop_table('tenant')
    op.drop_index(op.f('ix_data_source_name'), table_name='data_source')
    op.drop_table('data_source')
    # ### end Alembic commands ###
